### PR TITLE
feat: expose the additionalFilters for fine-grained host filtering

### PR DESCRIPTION
**Pull request by skateman**
My idea is to expose the `additionalFilters` on the `CyndiPipeline` CRD for a more fine-grained filtering of hosts:
```yaml
additionalFilters:
  - name: insightsOnly
     type: "com.redhat.insights.kafka.connect.transforms.Filter"
     if: "!!record.headers().lastWithName('insights_id').value()"
     where: "(canonical_facts ? 'insights_id')"
```

The `name` attribute is trivial, the `where` is the SQL query that describes the filter in the SQL world, the rest of the params `type`, `if` describe the kafka filter that does exactly the same as the where in SQL.

This should allow us to filter hosts based on additional parameters...

### CODE REVIEW

**Comment by fijshion** [comment]
the code looks good, I will do some sanity testing on my machine today. Could you add docs to the readme describing the new fields?

**Comment by skateman** [comment]
@fijshion I would like to, but I don't know where exactly, couldn't find any documentation of any existing field 😞

**Comment by fijshion** [comment]
A new section will work for now. This is the most confusing field and I imagine there will be questions about it if other teams want to use it.

**Comment by fijshion** [comment]
you could also add it to the platform docs here: https://consoledot.pages.redhat.com/docs/dev/services/inventory.html#cyndi. Although I prefer keeping docs in the project readme.

**Review by fijshion — APPROVED** [review]

**Pull request merged**
